# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/users/signin/ HTTP/1.1
content-type: application/json
Authorization: 4617016dfb228ce964b7cd42fa19f9ce05883542df8ed67b32a9fba2f79a

{
	"email": "test2@gmail.com",
	"password": "hello"
}