# Generated by Django 3.2.6 on 2021-10-28 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50, verbose_name='Artist'),
            preserve_default=False,
        ),
    ]
