# Generated by Django 3.2.6 on 2021-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Description'),
        ),
    ]
